import { Inter } from "next/font/google";
import Link from 'next/link'
//import "./globals.css";
import "./globalstyle.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="head-banner">
        <span className="logo">Quest Log</span>
        <div className="menuOptions"> 
          <Link href="/quests">Quests</Link> 
          <Link href="/rewards">Rewards</Link> 
          <Link href="/shop">Shop</Link>
        </div>
        </div>
        <div className="application">
        {children}
        </div>
        </body>
    </html>
  );
}
